apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-google-workspace-mcp
  labels:
    app: google-workspace-mcp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: google-workspace-mcp